// Paste your Elevator Pitch sentences here.
// Provide an array of strings. Each string is a full sentence (include spaces/punctuation).
// The game can apply adaptive timing based on length; no need to tag difficulty.
// Keep sentences within 8–90 characters for best pacing.
// Example entries are placeholders you can replace.

window.ELEVATOR_PITCH_SENTENCES =
[
  // Easy — 8–12 characters
  
  // Medium — 15–30 characters

  // Hard — 30–60 characters
  "The company was founded in 2020.",
  "It provides infrastructure for Web3 applications.",
  "The consensus protocol used by Espresso is called HotShot.",
  "The custom data availability layer is named TiramisuDA.",
  "TiramisuDA is designed for high performance and resilience.",
  "It supports both optimistic and ZK-rollups.",
  "Espresso helps rollups to decentralize their sequencers.",
  "MEV stands for Maximal Extractable Value.",
  "It provides a marketplace for shared sequencing.",
  "This creates a competitive environment for sequencing.",
  "It can lead to better revenue for L2s and rollups.",
  "The Espresso Sequencer is a key product of Espresso Systems.",
  "It offers decentralized sequencing as a service.",
  "It helps in achieving credible neutrality for rollups.",
  "The Espresso Network is currently in its Mainnet 0 release.",
  "The mainnet is supported by 100 decentralized nodes.",
  "Espresso is an EigenLayer Actively Validated Service (AVS).",
  "It uses restaked Ether (ETH) to enhance its security.",
  "Espresso is compatible with various rollup stacks.",
  "Investors include Andreessen Horowitz and Sequoia Capital.",
  "The company is headquartered in Menlo Park, California.",
  "They have published academic papers on their technology.",
  "The software is open-source and available on GitHub.",
  "The codebase is primarily written in Rust and Solidity.",
  "Espresso is designed to be modular and customizable.",
  "It supports interoperability with other blockchain networks.",
  "Espresso utilizes zero-knowledge proofs for privacy.",
  "This allows for confidential transactions on the network.",
  "It also helps in reducing latency and transaction fees.",
  "The platform provides SDKs and APIs for developers.",
  "Extensive documentation and community support are available.",
  "Espresso aims to unify the fragmented Layer-2 ecosystem.",
  "This creates a more unified liquidity and user experience.",
  "It mitigates cross-chain fragmentation challenges.",
  "It improves pre-confirmation trust and security.",
  "It aims to support projects building cross-chain solutions.",
  "Espresso's technology is continuously evolving and improving.",

  // Expert — 40–90 characters
  "Espresso Systems is a company focused on blockchain scaling and privacy solutions.",
  "Espresso Systems is developing a decentralized network called Espresso.",
  "Espresso is designed as a global confirmation layer for rollups.",
  "It aims to provide fast and reliable transaction confirmations.",
  "Espresso uses a Byzantine Fault Tolerant (BFT) consensus protocol.",
  "HotShot enables transaction confirmations within a few seconds.",
  "Espresso also offers a low-cost data availability (DA) layer.",
  "It helps in reducing the cost of data availability for applications.",
  "Espresso combines HotShot consensus with the TiramisuDA layer.",
  "The system is designed to be a shared public good for rollups.",
  "Centralized sequencers are a single point of failure for rollups.",
  "Espresso's decentralized nature enhances resilience and neutrality.",
  "It addresses the issue of monopolistic behavior by centralized sequencers.",
  "Espresso supports fair ordering and private mempools to mitigate MEV.",
  "Espresso aims to reduce the negative impacts of MEV on users.",
  "In this marketplace, Layer-2 chains can sell blockspace to proposers.",
  "The sequencer enhances interoperability between different rollups.",
  "It enables cheaper, faster, and safer cross-rollup messaging and bridging.",
  "Espresso confirmations are faster than waiting for Ethereum L1 finality.",
  "Espresso's finality is achieved in seconds, compared to minutes on Ethereum.",
  "The plan is to scale to more nodes and enable permissionless participation.",
  "This aligns Espresso's security with Ethereum's security model.",
  "These include Arbitrum Orbit, Cartesi, OP Stack, and Polygon CDK.",
  "Molten Network has integrated with Espresso for faster cross-chain trading.",
  "LogX is another project that has joined the Espresso ecosystem.",
  "Espresso Systems was co-founded by Ben Fisch and Benedikt Bünz.",
  "The team has expertise in blockchain architecture and cryptography.",
  "Espresso Systems has raised significant funding from various investors.",
  "Espresso Systems is actively involved in research and development.",
  "Developers can build dApps with configurable privacy and security.",
  "Espresso's efficient consensus mechanism increases transaction throughput.",
  "It enables seamless interaction between applications on different chains.",
  "Espresso's vision is to create a more interconnected and scalable blockchain future.",
  "They are working towards a more decentralized and user-centric Web3.",
  "Espresso's technology can prevent sequencer equivocation and reorgs.",
  "It reduces finality risk for solvers in intent-based systems.",
  "The network supports cross-chain arbitrage without intermediate bridging.",
  "It allows for atomic transactions that span multiple networks.",
  "Shared liquidity pools can be accessed from any connected chain.",
  "Espresso offers a solution to the centralized sequencer problem.",
  "Espresso is a key infrastructure provider for the Web3 ecosystem.",
  "It offers a path to decentralization without sacrificing performance.",
  "Espresso is building the tools for a private and scalable crypto future.",
  "The Espresso marketplace allows L2s to retain their sovereignty.",
  "They can set a minimum threshold for participating in the marketplace.",
  "The Espresso Network provides a robust pre-confirmation of blocks.",
  "Node operators on the Espresso Network earn rewards for their participation.",
  "Figment is one of the node operators on the Espresso network.",
  "Espresso is working on expanding its ecosystem and partnerships.",
  "They are focused on driving innovation in the cross-chain space.",
  "The Brew House is an accelerator program by Espresso Systems.",
  "Espresso is positioned to play a crucial role in the future of Ethereum scaling.",
  "It provides a neutral and open platform for the entire ecosystem.",
  "The project is committed to the principles of decentralization and security.",
  "They are actively working on future upgrades and enhancements.",
  "Espresso is a promising project with the potential to transform the blockchain landscape."
];



